name = "ferror"
author = "Jason Christopherson"
license = "GPL-3"
description = "A library to assist with error handling in Fortran projects."
homepage = "https://github.com/jchristopherson/ferror"
keywords = ["Fortran error handling"]

[build]
auto-executables = false
auto-examples = false
auto-tests = false

[library]
source-dir = "src"

[install]
library = true

[[test]]
name = "ferror_test"
source-dir = "test"
main = "ferror_test.f90"

[[test]]
name = "ferror_test_c"
source-dir = "test"
main = "ferror_test_c.c"

[[examples]]
name = "ferror_example_1"
source-dir = "examples"
main = "ferror_example_1.f90"

[[examples]]
name = "ferror_example_2"
source-dir = "examples"
main = "ferror_example_2.f90"

[[examples]]
name = "ferror_example_1c"
source-dir = "examples"
main = "ferror_example_1c.c"

[[examples]]
name = "ferror_example_2c"
source-dir = "examples"
main = "ferror_example_2c.c"
